import {NextRequest,NextResponse} from "next/server";
export const runtime="nodejs";
const LABELS:Record<string,string>={"insurance-type":"Insurance type","full-name":"Full name","date-of-birth":"Date of birth",phone:"Phone",email:"Email",address:"Home address","vehicle-vin":"Vehicle VIN","vehicle-year":"Vehicle year",vehicle:"Make and model","vehicle-use":"Primary use","annual-miles":"Estimated annual miles","current-insurer":"Current insurer","additional-auto":"Additional drivers or vehicles","property-address":"Property address","property-type":"Property type",occupancy:"Occupancy","year-built":"Year built","square-footage":"Approximate square footage","current-home-insurer":"Current home insurer","home-claims":"Claims in last 5 years","life-type":"Life insurance type","coverage-amount":"Coverage amount","term-length":"Term length","coverage-purpose":"Primary purpose","tobacco-use":"Tobacco or nicotine use","general-health":"General health",height:"Height",weight:"Weight","existing-life-insurance":"Existing life insurance",notes:"Notes","sms-consent":"SMS consent"};
const clean=(v:unknown,max=2000)=>String(v??"").replace(/\u0000/g,"").trim().slice(0,max);
const esc=(s:string)=>s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");
const validEmail=(s:string)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s);
export async function POST(req:NextRequest){
 try{
  const key=process.env.RESEND_API_KEY;
  if(!key)return NextResponse.json({error:"Quote email service is not configured yet."},{status:500});
  const body=await req.json();
  if(!body||typeof body!=="object"||Array.isArray(body))return NextResponse.json({error:"Invalid form data."},{status:400});
  const data:Record<string,string>={};for(const [k,v] of Object.entries(body as Record<string,unknown>))data[k]=clean(v);
  const name=clean(data["full-name"],120),email=clean(data.email,254),phone=clean(data.phone,80),coverage=clean(data["insurance-type"],30).toLowerCase();
  if(!name||!phone||!validEmail(email))return NextResponse.json({error:"Please complete your name, phone number, and a valid email."},{status:400});
  if(!["auto","home","life"].includes(coverage))return NextResponse.json({error:"Please select Auto, Home, or Life."},{status:400});
  const rows=Object.entries(data).filter(([,v])=>v!=="").map(([k,v])=>`<tr><td style="padding:10px 12px;border-bottom:1px solid #e6e8eb;font-family:Arial,Helvetica,sans-serif;font-size:13px;line-height:19px;color:#627083;font-weight:700;vertical-align:top;width:38%;">${esc(LABELS[k]??k)}</td><td style="padding:10px 12px;border-bottom:1px solid #e6e8eb;font-family:Arial,Helvetica,sans-serif;font-size:14px;line-height:20px;color:#13243c;vertical-align:top;">${esc(k==="sms-consent"?(v==="yes"?"Yes":"No"):v)}</td></tr>`).join("");
  const subject=`New ${coverage.toUpperCase()} quote request — ${name}`;
  const text=["New David's Insurance quote request","",...Object.entries(data).filter(([,v])=>v!=="").map(([k,v])=>`${LABELS[k]??k}: ${v}`)].join("\n");
  const html=`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="IE=edge"></head><body style="margin:0;background-color:#f7f5f0;"><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td align="center" bgcolor="#f7f5f0" style="padding-top:28px;padding-right:14px;padding-bottom:28px;padding-left:14px;background-color:#f7f5f0;"><table width="100%" cellpadding="0" cellspacing="0" border="0" style="max-width:640px;background-color:#ffffff;"><tr><td bgcolor="#142b4b" style="padding-top:24px;padding-right:28px;padding-bottom:24px;padding-left:28px;background-color:#142b4b;"><p style="margin:0 0 6px 0;font-family:Arial,Helvetica,sans-serif;font-size:12px;line-height:18px;color:#f8a496;font-weight:700;">DAVID'S INSURANCE</p><h1 style="margin:0;font-family:Arial,Helvetica,sans-serif;font-size:24px;line-height:31px;color:#ffffff;font-weight:700;">New ${esc(coverage.toUpperCase())} quote request</h1></td></tr><tr><td bgcolor="#ffffff" style="padding-top:24px;padding-right:28px;padding-bottom:10px;padding-left:28px;background-color:#ffffff;"><p style="margin:0 0 6px 0;font-family:Arial,Helvetica,sans-serif;font-size:18px;line-height:25px;color:#13243c;font-weight:700;">${esc(name)}</p><p style="margin:0;font-family:Arial,Helvetica,sans-serif;font-size:14px;line-height:21px;color:#627083;">${esc(phone)} · ${esc(email)}</p></td></tr><tr><td bgcolor="#ffffff" style="padding-top:10px;padding-right:28px;padding-bottom:28px;padding-left:28px;background-color:#ffffff;"><table width="100%" cellpadding="0" cellspacing="0" border="0" style="border:1px solid #e6e8eb;">${rows}</table></td></tr></table></td></tr></table></body></html>`;
  const r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({from:process.env.QUOTE_FROM_EMAIL||"David's Insurance Website <quotes@pacificacrm.com>",to:[process.env.QUOTE_TO_EMAIL||"davidscarinsurance@gmail.com"],subject,text,html,reply_to:email}),cache:"no-store"});
  if(!r.ok){console.error("Resend error",r.status,await r.text());return NextResponse.json({error:"We could not send your request. Please try again."},{status:502});}
  return NextResponse.json({ok:true});
 }catch(e){console.error("Quote form error",e);return NextResponse.json({error:"We could not send your request. Please try again."},{status:500});}
}
